pipelines:
  pipe1:
    group: simple
    materials:
      hello-go-repo:
        git: https://github.com/amasucci/hello-go.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              elastic_profile_id: "demo-app"
              tasks:
               - exec: # indicates type of task
                   command: go build
